services:
  - type: web
    name: unionapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn unionapp.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: unionapp.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: DATABASE_URL
        value: postgresql://uniondb_user:a8Dm6nOJvIGaNM2yyI92pXzJdZhTAXOP@dpg-d25qlnmuk2gs73bh1rh0-a/uniondb
  postDeployCommand: python manage.py migrate
