# Generated by Django 5.2.4 on 2025-08-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_notice_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='posted_at',
            new_name='created_at',
        ),
    ]
